spring.application.name=base

# JWT Configuration (Necessario variável de ambiente para secret, caso contrario sera usado o valor padrão)
jwt.secret=${JWT_SECRET:12345678910ABCDEFGHIJKLMNOPQRSTUVWXYZ}
jwt.expiration=86400000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/basedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Server Configuration
server.port=8080
